name: 5 Days in Iceland
favicon: null
layout_spectrum: 0.22224
typography_spectrum: 0.8935691048391163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f5'
    - '#a7ccc5'
    - '#424041'
    - '#757374'
    - '#989699'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
