name: 5 Days in Iceland
favicon: null
layout_spectrum: 0.1007900689728558
typography_spectrum: 0.8935691048391163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#534b49'
    - '#7f8084'
    - '#191b28'
    - '#edcbcc'
  brandStrength: 0.1875
  lightness: 0.5199042055755854
  saturation: 0
  rhythmicContrast: 0.05359649797901511
purpose: []
